### ISSUE TITLE
Setting an environment variable

### ISSUE THREAD

**Issue by p-j-smith** [matlab-actions/run-tests#19]
Hi, I am using this action in a workflow but I'd like to be able to set an environment variable before running the tests. Is this possible using the `run-tests` action?

If not, being able to do something like this would be really useful:

```yaml
      - name: Run tests and generate artifacts
        uses: matlab-actions/run-tests@v1
        with:
          set-env: MY_ENV_VAR=/path/to/folder
          code-coverage-cobertura: code-coverage/coverage.xml
```
Thanks!
