### ISSUE TITLE
Unable to pass two source-folder in github action yml file

### ISSUE THREAD

**Issue by tosandip** [matlab-actions/run-tests#42]
when adding two folders in source-folder (https://github.com/tosandip/ci-configuration-examples/actions/runs/5980283253/workflow#L35) , it converts into this 

  addpath(genpath('code samplecode'));

which is incorrect leading to the error I see in the matlab runner: https://github.com/tosandip/ci-configuration-examples/actions/runs/5980283253/job/16226096632#step:4:579

**Comment by mcafaro** [comment]
You need to use a colon-separated or semicolon-separated list to specify multiple folders.

Try:
```
      - name: Run all tests
        uses: matlab-actions/run-tests@v1
        with:
          source-folder: code; samplecode
```
